pub(in crate::wgpu_backend) mod backdrops;
pub(in crate::wgpu_backend) mod composites;
pub(in crate::wgpu_backend) mod draws;
pub(in crate::wgpu_backend) mod effects;
pub(in crate::wgpu_backend) mod instructions;
pub(in crate::wgpu_backend) mod leaf_batches;
pub(in crate::wgpu_backend) mod shape_effects;
pub(in crate::wgpu_backend) mod shapes;
pub(in crate::wgpu_backend) mod targets;
pub(in crate::wgpu_backend) mod textures;
mod uniforms;
