// TODO: This is needed to avoid false positives generated by the repr(C) expansion in compiler 1.89
#![allow(unused)]
/// Example: cached shader-generated box shadows with rounded corners.
///
/// Each card supplies a stable geometry id. Grafo rasterizes its local coverage mask and
/// executes the shadow shader once, then reuses the exact GPU result on later frames.
///
/// The scene shows several cards with different shadow parameters:
/// - A card with a soft, large-radius shadow
/// - A card with a tight, dark shadow
/// - A card with a colored shadow and an offset
use futures::executor::block_on;
use grafo::{BorderRadii, Color, Shape, ShapeDrawCommandOptions, ShapeEffectConfig, Stroke};
use std::sync::Arc;
use winit::application::ApplicationHandler;
use winit::event::WindowEvent;
use winit::event_loop::{ActiveEventLoop, EventLoop};
use winit::window::{Window, WindowId};

const BOX_SHADOW_EFFECT: u64 = 1;

/// Parameters for the coverage-mask shadow shader.
#[repr(C)]
#[derive(Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct BoxShadowParams {
    shadow_color: [f32; 4],
    offset: [f32; 2],
    sigma: f32,
    _padding: f32,
}

struct CardSpec {
    geometry_id: u64,
    position: (f32, f32),
    size: (f32, f32),
    corner_radius: f32,
    shadow_sigma: f32,
    shadow_offset: [f32; 2],
    shadow_rgba: [f32; 4],
    card_color: Color,
}

/// Creates a card with a box shadow effect attached directly to it.
///
/// The shadow is computed analytically in the shader and composited behind the
/// card content. No wrapper shape needed — the offscreen texture is full-screen
/// and the effect output is a fullscreen quad, so shadow pixels outside the
/// card's bounds render correctly.
///
/// Returns the node id of the card, so children can be added to it.
fn draw_card(renderer: &mut grafo::Renderer, card_spec: CardSpec) -> usize {
    let (x, y) = card_spec.position;
    let (width, height) = card_spec.size;
    let card_shape = Shape::rounded_rect(
        [(x, y), (x + width, y + height)],
        BorderRadii::new(card_spec.corner_radius),
        Stroke::new(0.0_f32, Color::TRANSPARENT),
    );
    let card = renderer
        .add_shape(
            card_shape,
            None,
            Some(card_spec.geometry_id),
            ShapeDrawCommandOptions::new().color(card_spec.card_color),
        )
        .unwrap();

    // The shader samples in physical texels, so convert sigma and offset from logical
    // pixels to physical pixels using the current DPI scale factor. The outsets stay in
    // logical units: the renderer converts them to physical pixels internally.
    let scale_factor = renderer.scale_factor() as f32;
    let [red, green, blue, alpha] = card_spec.shadow_rgba;
    let params = BoxShadowParams {
        shadow_color: [red * alpha, green * alpha, blue * alpha, alpha],
        offset: [
            card_spec.shadow_offset[0] * scale_factor,
            card_spec.shadow_offset[1] * scale_factor,
        ],
        sigma: card_spec.shadow_sigma * scale_factor,
        _padding: 0.0,
    };
    let blur_outset = card_spec.shadow_sigma * 3.0;

    renderer
        .set_shape_effect(
            card,
            BOX_SHADOW_EFFECT,
            bytemuck::bytes_of(&params),
            ShapeEffectConfig::new().outsets(
                blur_outset + (-card_spec.shadow_offset[0]).max(0.0),
                blur_outset + (-card_spec.shadow_offset[1]).max(0.0),
                blur_outset + card_spec.shadow_offset[0].max(0.0),
                blur_outset + card_spec.shadow_offset[1].max(0.0),
            ),
        )
        .expect("Failed to set box shadow effect");

    card
}

/// The shader works for any tessellated shape, not only rectangles.
///
/// The blur is separable: pass 1 blurs the coverage mask horizontally, pass 2 blurs the
/// intermediate result vertically and applies the shadow color. This keeps the same
/// Gaussian result as a 2D kernel at O(radius) sampling cost per pass instead of
/// O(radius^2) in a single pass.
const BOX_SHADOW_HORIZONTAL_WGSL: &str = r#"
struct Params {
    shadow_color: vec4<f32>,
    offset: vec2<f32>,
    sigma: f32,
    _padding: f32,
}
@group(1) @binding(0) var<uniform> params: Params;

@fragment
fn effect_main(@location(0) uv: vec2<f32>) -> @location(0) vec4<f32> {
    let texture_size = vec2<f32>(textureDimensions(t_input));
    let sigma = max(params.sigma, 0.0001);
    let radius = min(i32(ceil(sigma * 3.0)), 48);
    let source_uv = uv - params.offset / texture_size;
    var coverage = 0.0;
    var total_weight = 0.0;
    for (var x = -radius; x <= radius; x++) {
        let weight = exp(-f32(x * x) / (2.0 * sigma * sigma));
        let sample_uv = source_uv + vec2<f32>(f32(x), 0.0) / texture_size;
        coverage += textureSample(t_input, s_input, sample_uv).a * weight;
        total_weight += weight;
    }
    // Pass only the horizontally blurred coverage forward; the color is applied in pass 2.
    return vec4<f32>(0.0, 0.0, 0.0, coverage / max(total_weight, 0.0001));
}
"#;

const BOX_SHADOW_VERTICAL_WGSL: &str = r#"
struct Params {
    shadow_color: vec4<f32>,
    offset: vec2<f32>,
    sigma: f32,
    _padding: f32,
}
@group(1) @binding(0) var<uniform> params: Params;

@fragment
fn effect_main(@location(0) uv: vec2<f32>) -> @location(0) vec4<f32> {
    let texture_size = vec2<f32>(textureDimensions(t_input));
    let sigma = max(params.sigma, 0.0001);
    let radius = min(i32(ceil(sigma * 3.0)), 48);
    var coverage = 0.0;
    var total_weight = 0.0;
    for (var y = -radius; y <= radius; y++) {
        let weight = exp(-f32(y * y) / (2.0 * sigma * sigma));
        let sample_uv = uv + vec2<f32>(0.0, f32(y)) / texture_size;
        coverage += textureSample(t_input, s_input, sample_uv).a * weight;
        total_weight += weight;
    }
    return params.shadow_color * (coverage / max(total_weight, 0.0001));
}
"#;

#[derive(Default)]
struct App<'a> {
    window: Option<Arc<Window>>,
    renderer: Option<grafo::Renderer<'a>>,
}

impl<'a> ApplicationHandler for App<'a> {
    fn resumed(&mut self, event_loop: &ActiveEventLoop) {
        let window = Arc::new(
            event_loop
                .create_window(
                    Window::default_attributes().with_title("Grafo – Analytical Box Shadow"),
                )
                .unwrap(),
        );

        let window_size = window.inner_size();
        let scale_factor = window.scale_factor();
        let physical_size = (window_size.width, window_size.height);

        let mut renderer = block_on(grafo::Renderer::new(
            window.clone(),
            physical_size,
            scale_factor,
            true,
            false,
            1,
        ));

        // Load the box shadow effect shader once (horizontal + vertical blur passes)
        renderer
            .load_effect(
                BOX_SHADOW_EFFECT,
                &[BOX_SHADOW_HORIZONTAL_WGSL, BOX_SHADOW_VERTICAL_WGSL],
            )
            .expect("Failed to compile box shadow effect");

        self.window = Some(window);
        self.renderer = Some(renderer);
    }

    fn window_event(
        &mut self,
        event_loop: &ActiveEventLoop,
        window_id: WindowId,
        event: WindowEvent,
    ) {
        let Some(window) = &self.window else { return };
        let Some(renderer) = &mut self.renderer else {
            return;
        };

        if window_id != window.id() {
            return;
        }

        match event {
            WindowEvent::CloseRequested => event_loop.exit(),
            WindowEvent::Resized(physical_size) => {
                let new_size = (physical_size.width, physical_size.height);
                renderer.resize(new_size);
                window.request_redraw();
            }
            WindowEvent::RedrawRequested => {
                let (pw, ph) = renderer.size();
                let pw = pw as f32;
                let ph = ph as f32;

                // ── Scene background ─────────────────────────────────────
                let scene_bg = Shape::rect(
                    [(0.0, 0.0), (pw, ph)],
                    Stroke::new(0.0_f32, Color::TRANSPARENT),
                );
                renderer
                    .add_shape(
                        scene_bg,
                        None,
                        None,
                        ShapeDrawCommandOptions::new().color(Color::rgb(235, 235, 240)),
                    )
                    .unwrap();

                // ── Card 1: Soft, large shadow ───────────────────────────
                draw_card(
                    renderer,
                    CardSpec {
                        geometry_id: 1,
                        position: (80.0, 60.0),
                        size: (280.0, 180.0),
                        corner_radius: 16.0,
                        shadow_sigma: 12.0,
                        shadow_offset: [0.0, 4.0],
                        shadow_rgba: [0.0, 0.0, 0.0, 0.35],
                        card_color: Color::WHITE,
                    },
                );

                // ── Card 2: Tight, dark shadow ───────────────────────────
                draw_card(
                    renderer,
                    CardSpec {
                        geometry_id: 2,
                        position: (420.0, 60.0),
                        size: (280.0, 180.0),
                        corner_radius: 8.0,
                        shadow_sigma: 4.0,
                        shadow_offset: [0.0, 2.0],
                        shadow_rgba: [0.0, 0.0, 0.0, 0.6],
                        card_color: Color::WHITE,
                    },
                );

                // ── Card 3: Colored shadow with offset ───────────────────
                draw_card(
                    renderer,
                    CardSpec {
                        geometry_id: 3,
                        position: (80.0, 320.0),
                        size: (280.0, 180.0),
                        corner_radius: 20.0,
                        shadow_sigma: 16.0,
                        shadow_offset: [8.0, 8.0],
                        shadow_rgba: [0.2, 0.0, 0.5, 0.4],
                        card_color: Color::rgb(240, 245, 255),
                    },
                );

                // ── Card 4: Subtle elevation shadow ──────────────────────
                draw_card(
                    renderer,
                    CardSpec {
                        geometry_id: 4,
                        position: (420.0, 320.0),
                        size: (280.0, 180.0),
                        corner_radius: 12.0,
                        shadow_sigma: 8.0,
                        shadow_offset: [0.0, 6.0],
                        shadow_rgba: [0.0, 0.0, 0.0, 0.2],
                        card_color: Color::rgb(255, 250, 240),
                    },
                );

                // ── Render ───────────────────────────────────────────────
                match renderer.render() {
                    Ok(_) => {
                        renderer.clear_draw_queue();
                    }
                    Err(
                        wgpu::CurrentSurfaceTexture::Lost | wgpu::CurrentSurfaceTexture::Outdated,

                    ) => renderer.resize(renderer.size()),

                    Err(
                        wgpu::CurrentSurfaceTexture::Timeout
                        | wgpu::CurrentSurfaceTexture::Occluded,

                    ) => {
                        // The window is not visible yet (still appearing, minimized, or fully
                        // covered). Ask for another redraw instead of dropping the frame for
                        // good — winit does not request one when the window becomes visible.
                        renderer.clear_draw_queue();
                        window.request_redraw();

                    }
                    Err(e) => eprintln!("{e:?}"),
                }
            }
            _ => {}
        }
    }
}

pub fn main() {
    env_logger::init();
    let event_loop = EventLoop::new().expect("To create the event loop");

    let mut app = App::default();
    let _ = event_loop.run_app(&mut app);
}
